name: Deploy to AWS on Master Push

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /path/to/your/app
          echo "Stopping and removing existing containers..."
          docker-compose down
          echo "Removing old images..."
          docker rmi $(docker images -q your-image-name) || true
          echo "Pulling latest code..."
          git pull origin master
          echo "Building and starting containers..."
          docker-compose up -d --build