name: Deploy Gateway Service

on:
  push:
    branches: [main, master]

env:
  AWS_SERVER_IP: ${{ secrets.AWS_SERVER_IP }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
  PROJECT_DIR: /home/ubuntu/demo-gateway-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          known_hosts: 'just-a-placeholder'

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_SERVER_IP }} "
            # Navigate to project directory
            cd $PROJECT_DIR || exit 1
            
            # Stop and remove existing containers with their volumes
            docker-compose down --volumes --remove-orphans || true
            
            # Pull the latest code
            git fetch --all
            git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
            git pull origin $(git rev-parse --abbrev-ref HEAD)
            
            # Rebuild and start containers
            docker-compose up --build --force-recreate -d
            
            # Verify deployment
            echo 'Current containers:'
            docker ps -a
            echo 'Gateway service logs:'
            docker-compose logs --tail=20
          "
